# Generated by Django 4.2.19 on 2025-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "author_type",
                    models.CharField(
                        choices=[("선생", "선생"), ("일반", "일반"), ("기업", "기업")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("region", models.CharField(max_length=50)),
                ("pay_type", models.CharField(max_length=20)),
                ("pay_amount", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UsedInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("region", models.CharField(max_length=50)),
                ("condition", models.CharField(max_length=20)),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="location",
        ),
        migrations.AddField(
            model_name="lesson",
            name="delivery",
            field=models.CharField(default="온라인", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lesson",
            name="region",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
